server:
  port: 9002

spring:
  security:
    oauth2:
      client:
        registration:
          stackoverflow:
            provider:      "stackoverflow"
            client-name:   "Stackoverflow"
            client-id:     "[env]"
            client-secret: "[env]"
            redirect-uri:  "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: "authorization_code"
            scope:
              - read_inbox
              - no_expiry
              - private_info
        provider: 
          stackoverflow:
            authorization-uri:   "https://stackoverflow.com/oauth"
            token-uri:           "https://stackoverflow.com/oauth/access_token/json"
            user-info-uri:       "https://api.stackexchange.com/2.2/me"
            user-name-attribute: "user_id"

app:  oauth2:    stackoverflow:      key: "[env]"
      order: "desc"
      sort: "reputation"
      site: "stackoverflow"

logging:
  level:
    com.example: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG